version: 0.0
os: linux
files:
  - source: artisan
    destination: /var/www/woa
  - source: composer.json
    destination: /var/www/woa
  - source: composer.lock
    destination: /var/www/woa
  - source: app
    destination: /var/www/woa/app
  - source: bootstrap
    destination: /var/www/woa/bootstrap
  - source: config
    destination: /var/www/woa/config
  - source: database
    destination: /var/www/woa/database
  - source: public
    destination: /var/www/woa/public
  - source: resources
    destination: /var/www/woa/resources
  - source: routes
    destination: /var/www/woa/routes
  - source: storage
    destination: /var/www/woa/storage
  - source: tests
    destination: /var/www/woa/tests
permissions:
  - object: /var/www/woa
    owner: woa
    group: woa
hooks:
  BeforeInstall:
    - location: scripts/BeforeInstall.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/AfterInstall.sh
      timeout: 300
      runas: woa

