name: 'ecspresso deploy'
description: 'ecspresso deploy'
inputs:
  AWS_ACCOUNT_ID:
    description: 'AWS account id'
    required: true
  ENVIRONMENT:
    description: 'development, production'
    required: true
  SERVER_TYPE:
    description: 'webapp'
    required: true

runs:
  using: "composite"
  steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::${{ inputs.AWS_ACCOUNT_ID }}:role/github_actions
        aws-region: ap-northeast-1

    - name: ecspresso deploy
      uses: kayac/ecspresso@v2
      with:
        version: latest

    - shell: bash
      run: ecspresso deploy --config .github/ecspresso/${{ inputs.ENVIRONMENT }}/service_${{ inputs.SERVER_TYPE }}/ecspresso.yml --ext-str "Tag=${{ github.sha }}"
