<?php

return [
    'csv' => [
        'header'                    => [
            'sf_order_id',
            'sf_account_id',
            'site_id',
            'job_id',
            'title',
            'employment_type',
            'detail',
            'salary',
            'worktime',
            'closest',
            'dayoff',
            'osusume_comment',
            'office_name',
            'office_name_kana',
            'company_name',
            'company_name_kana',
            'medical_category',
            'facilities',
            'business',
            'hp_url',
            'job_type',
            'postal_code',
            'addr1_name',
            'addr2_name',
            'addr_street',
            'g_latitude',
            'g_longitude',
            'order_name',
            'ad_attract_stop_flag',
            'inq_number',
            'publicly_flag',
            'station1',
            'station2',
            'station3',
            'minutes_walk1',
            'minutes_walk2',
            'minutes_walk3',
            'prev_year_bounus',
            'annual_income_min',
            'annual_income_max',
            'nenkankyuujitsu',
            'recommend_comment',
            'account_name_flag',
            'business_memo',
            'torikaku_status',
            'order_pr_title',
            'order_status',
            'human_resource',
            'last_confirmed_datetime',
        ],
        // CSVのヘッダー項目とSF項目の紐付き
        'mapping_header_to_db_item' => [
            'sf_order_id'             => 'Id',
            'sf_account_id'           => 'ID__c',
            'site_id'                 => 'web_site__c',
            'job_id'                  => 'request_number__c',
            'title'                   => 'osusumekomentp__c',
            'employment_type'         => 'koyoukeitai__c',
            'detail'                  => 'KO_Gyomunaiyoubikou__c',
            'salary'                  => 'KO_Kyuyo__c',
            'worktime'                => 'KO_WorkingHours__c',
            'closest'                 => 'KO_Transportation__c',
            'dayoff'                  => 'kyujitukyuka__c',
            'osusume_comment'         => 'osusumekomentqjin__c',
            'office_name'             => 'Account__r.Name',
            'office_name_kana'        => 'Account__r.Field17__c',
            'company_name'            => 'Account__r.Field1__c',
            'company_name_kana'       => 'Account__r.Field18__c',
            'medical_category'        => 'Account__r.Field6__c',
            'facilities'              => 'Account__r.Field42__c',
            'business'                => 'Account__r.sisetu_keitai_input__c',
            'hp_url'                  => 'Account__r.Field16__c',
            'job_type'                => 'boshu_shikaku__c',
            'postal_code'             => 'Account__r.BillingPostalCode',
            'addr1_name'              => 'Account__r.BillingState',
            'addr2_name'              => 'Account__r.BillingCity',
            'addr_street'             => 'Account__r.BillingStreet',
            'g_latitude'              => 'Account__r.GIdoNumber__c',
            'g_longitude'             => 'Account__r.GKeidoNumber__c',
            'order_name'              => 'Name',
            'ad_attract_stop_flag'    => 'Account__r.AC_Advt_Stop_Flag__c',
            'inq_number'              => 'inq_number__c',
            'publicly_flag'           => 'publicly_flag__c',
            'station1'                => 'moyorieki11__c',
            'station2'                => 'moyorieki22__c',
            'station3'                => 'moyorieki33__c',
            'minutes_walk1'           => 'Account__r.timeRequired1__c',
            'minutes_walk2'           => 'Account__r.timeRequired2__c',
            'minutes_walk3'           => 'Account__r.timeRequired3__c',
            'prev_year_bounus'        => 'Field1__c',
            'annual_income_min'       => 'KO_annual_income_min__c',
            'annual_income_max'       => 'KO_annual_income_max__c',
            'nenkankyuujitsu'         => 'nenkankyuujitsu__c',
            'recommend_comment'       => 'KO_RecommendedComments__c',
            'account_name_flag'       => 'KO_AccountNameCloseSummary__c',
            'business_memo'           => 'syoudannaiyousonotamemo__c',
            'torikaku_status'         => 'DealStatus__c',
            'order_pr_title'          => 'order_pr_title__c',
            'order_status'            => 'KO_od_status__c',
            'human_resource'          => 'KO_IdealCandidate__c',
            'last_confirmed_datetime' => 'KO_KJA_order_presence_date__c',
        ],
    ],
];
