<?php

return [
    'memory_limit'                     => '512M',
    'conversion_sf_to_web'             => [
        'employment_type' => [
            '常勤'         => 1,
            '常勤(夜勤のみ)'   => 1,
            '常勤(日勤のみ)'   => 1,
            '常勤(日勤+夜勤)'  => 1,
            '常勤(夜勤あり)'   => 1,
            '常勤(夜勤なし)'   => 1,
            '非常勤'        => 2,
            '非常勤(夜勤のみ)'  => 2,
            '非常勤(日勤のみ)'  => 2,
            '非常勤(日勤+夜勤)' => 2,
            '非常勤(夜勤あり)'  => 2,
            '非常勤(夜勤なし)'  => 2,
        ],
        'dayoff'          => [
            '①' => '（１）',
            '②' => '（２）',
            '③' => '（３）',
            '④' => '（４）',
            '⑤' => '（５）',
        ],
        'job_type'        => [
            '柔道整復師（管理）'         => '1',
            '柔道整復師'             => '2',
            '鍼灸師'               => '3',
            'あん摩ﾏｯｻｰｼﾞ指圧師'      => '4',
            '国資学生（柔道整復）'        => '5',
            '国資学生（鍼灸）'          => '6',
            '国資学生（あん摩ﾏｯｻｰｼﾞ指圧）' => '7',
            '整体'                => '8',
            'ｶｲﾛﾌﾟﾗｸﾀｰ'         => '9',
            'ｱﾛﾏｾﾗﾋﾟｽﾄ'         => '10',
            'ﾘﾌﾚｸｿﾛｼﾞｽﾄ'        => '11',
            'ﾀｲ古式ｾﾗﾋﾟｽﾄ'        => '12',
            'ﾛﾐﾛﾐｾﾗﾋﾟｽﾄ'        => '13',
            'その他'               => '99',
        ],
        'business'        => [
            'グループホーム'       => '1',
            'サービス付き高齢者専用住宅' => '2',
            'ショートステイ事業所'    => '3',
            'デイケア事業所'       => '4',
            'デイサービス事業所'     => '5',
            '介護療養型医療施設'     => '6',
            '介護老人保健施設'      => '7',
            '企業'            => '8',
            '保育園(認可)'       => '9',
            '保育園(認可外)'      => '10',
            '小規模多機能'        => '11',
            '居宅介護支援事業所'     => '12',
            '往診・訪問診療'       => '13',
            '放課後等デイサービス'    => '14',
            '施術所'           => '15',
            '施設'            => '16',
            '有料老人ホーム'       => '17',
            '本部（施設）'        => '18',
            '特別養護老人ホーム'     => '19',
            '病院'            => '20',
            '福祉用具'          => '21',
            '給食委託会社'        => '22',
            '訪問マッサージ事業所'    => '23',
            '訪問リハビリ事業所'     => '24',
            '訪問介護事業所'       => '25',
            '訪問入浴事業所'       => '26',
            '訪問看護ステーション'    => '27',
            '訪問鍼灸事業所'       => '28',
            '診療所'           => '29',
            '軽費老人ホーム'       => '30',
            '重症心身障害児(者)施設'  => '31',
            '障害者施設'         => '32',
            'その他'           => '99',
        ],
        'salary'          => [
            '時間給'     => '時給',
            '万から'     => '万円から',
            '万以上'     => '万円以上',
            '万程'      => '万円程',
            '万 '      => '万円 ',
            '月給:'     => '月給',
            '年収:'     => '年収',
            '時給:'     => '時給',
            '日給:'     => '日給',
            '【月給】'    => '月給',
            '【年収】'    => '年収',
            '【時給】'    => '時給',
            '【日給】'    => '日給',
            '[月給]'    => '月給',
            '[年収]'    => '年収',
            '[時給]'    => '時給',
            '[日給]'    => '日給',
            '（月給）'    => '月給',
            '（年収）'    => '年収',
            '（時給）'    => '時給',
            '（日給）'    => '日給',
            '(月給)'    => '月給',
            '(年収)'    => '年収',
            '(時給)'    => '時給',
            '(日給)'    => '日給',
            '0000円'   => '万円',
            '0,000円'  => '万円',
            '0000000' => '000万円',
            '000000'  => '00万円',
            '00000'   => '0万円',
            '0000'    => '万円',
            '0,000'   => '万円',
            '万円万円'    => '万円',
        ],
    ],
    // 雇用形態が非常勤となるオーダー名
    'order_name_for_part_time'         => [
        '非常勤のみ',
        '非常勤ﾉﾐ',
    ],
    'csv_for_feed'                     => [
        'header' => [
            'job_id',
            'sf_order_id',
            'sf_account_id',
            'business_id',
            'inq_number',
            'employment_type',
            'detail',
            'salary',
            'worktime',
            'closest',
            'dayoff',
            'office_name',
            'office_name_kana',
            'company_name',
            'company_name_kana',
            'medical_category',
            'facilities',
            'hp_url',
            'job_type',
            'postal_code',
            'addr1',
            'addr1_name',
            'addr2',
            'addr2_name',
            'addr',
            'g_latitude',
            'g_longitude',
            'employ',
            'worklocation',
            'business',
            'station1',
            'station2',
            'station3',
            'ad_attract_stop_flag',
            'account_name_flag',
            'publicly_flag',
            'webpublicly_flag',
            'job_type_name_for_feed',
            'order_pr_title',
            'exist_order_flag',
        ],
    ],
    // 配列のキーとwoa_opportunityの紐付き
    'mapping_array_to_woa_opportunity' => [
        'job_id'               => [
            'db_column'            => 'job_id',
            'db_column_size_limit' => 11,
        ],
        'sf_order_id'          => [
            'db_column'            => 'sf_order_id',
            'db_column_size_limit' => 50,
        ],
        'sf_account_id'        => [
            'db_column'            => 'sf_account_id',
            'db_column_size_limit' => 50,
        ],
        'inq_number'           => [
            'db_column'            => 'inq_number',
            'db_column_size_limit' => 80,
        ],
        'employment_type'      => [
            'db_column'            => 'employment_type',
            'db_column_size_limit' => 100,
        ],
        'detail'               => [
            'db_column'            => 'detail',
            'db_column_size_limit' => 2000,
        ],
        'salary'               => [
            'db_column'            => 'salary',
            'db_column_size_limit' => 1000,
        ],
        'worktime'             => [
            'db_column'            => 'worktime',
            'db_column_size_limit' => 2000,
        ],
        'closest'              => [
            'db_column'            => 'closest',
            'db_column_size_limit' => 255,
        ],
        'dayoff'               => [
            'db_column'            => 'dayoff',
            'db_column_size_limit' => 255,
        ],
        'office_name'          => [
            'db_column'            => 'office_name',
            'db_column_size_limit' => 255,
        ],
        'office_name_kana'     => [
            'db_column'            => 'office_name_kana',
            'db_column_size_limit' => 255,
        ],
        'company_name'         => [
            'db_column'            => 'company_name',
            'db_column_size_limit' => 255,
        ],
        'company_name_kana'    => [
            'db_column'            => 'company_name_kana',
            'db_column_size_limit' => 255,
        ],
        'medical_category'     => [
            'db_column'            => 'medical_category',
            'db_column_size_limit' => 255,
        ],
        'facilities'           => [
            'db_column'            => 'facilities',
            'db_column_size_limit' => 255,
        ],
        'hp_url'               => [
            'db_column'            => 'hp_url',
            'db_column_size_limit' => 255,
        ],
        'business'             => [
            'db_column'            => 'business',
            'db_column_size_limit' => 255,
        ],
        'worklocation'         => [
            'db_column'            => 'worklocation',
            'db_column_size_limit' => 255,
        ],
        'job_type'             => [
            'db_column'            => 'job_type',
            'db_column_size_limit' => 50,
        ],
        'postal_code'          => [
            'db_column'            => 'postal_code',
            'db_column_size_limit' => 50,
        ],
        'addr1'                => [
            'db_column'            => 'addr1',
            'db_column_size_limit' => 11,
        ],
        'addr2'                => [
            'db_column'            => 'addr1',
            'db_column_size_limit' => 11,
        ],
        'addr'                 => [
            'db_column'            => 'addr',
            'db_column_size_limit' => 512,
        ],
        'g_latitude'           => [
            'db_column'            => 'g_latitude',
            'db_column_size_limit' => 11,
        ],
        'g_longitude'          => [
            'db_column'            => 'g_longitude',
            'db_column_size_limit' => 11,
        ],
        'employ'               => [
            'db_column'            => 'employ',
            'db_column_size_limit' => 255,
        ],
        'station1'             => [
            'db_column'            => 'station1',
            'db_column_size_limit' => 50,
        ],
        'station2'             => [
            'db_column'            => 'station2',
            'db_column_size_limit' => 50,
        ],
        'station3'             => [
            'db_column'            => 'station3',
            'db_column_size_limit' => 50,
        ],
        'minutes_walk1'        => [
            'db_column'            => 'minutes_walk1',
            'db_column_size_limit' => 11,
        ],
        'minutes_walk2'        => [
            'db_column'            => 'minutes_walk2',
            'db_column_size_limit' => 11,
        ],
        'minutes_walk3'        => [
            'db_column'            => 'minutes_walk3',
            'db_column_size_limit' => 11,
        ],
        'prev_year_bounus'     => [
            'db_column'            => 'prev_year_bounus',
            'db_column_size_limit' => 100,
        ],
        'annual_income_min'    => [
            'db_column'            => 'annual_income_min',
            'db_column_size_limit' => 11,
        ],
        'annual_income_max'    => [
            'db_column'            => 'annual_income_max',
            'db_column_size_limit' => 11,
        ],
        'nenkankyuujitsu'      => [
            'db_column'            => 'nenkankyuujitsu',
            'db_column_size_limit' => 11,
        ],
        'publicly_flag'        => [
            'db_column'            => 'publicly_flag',
            'db_column_size_limit' => 11,
        ],
        'webpublicly_flag'     => [
            'db_column'            => 'webpublicly_flag',
            'db_column_size_limit' => 11,
        ],
        'exist_order_flag'     => [
            'db_column'            => 'exist_order_flag',
            'db_column_size_limit' => 11,
        ],
        'ad_attract_stop_flag' => [
            'db_column'            => 'ad_attract_stop_flag',
            'db_column_size_limit' => 1,
        ],
        'order_pr_title'       => [
            'db_column'            => 'order_pr_title',
            'db_column_size_limit' => 255,
        ],
        'human_resource'       => [
            'db_column'            => 'human_resource',
            'db_column_size_limit' => 9000,
        ],
        'hw_flag'              => [
            'db_column'            => 'hw_flag',
            'db_column_size_limit' => 1,
        ],
    ],
    'invalid_order_name_list'          => [
        '【テスト】',
        '停止',
        '使用',
        '閉鎖',
        '要取確取得',
        '倒産',
        '廃業',
        '破産',
        '取引停止',
        '閉店',
        '撤退',
        '閉業',
        '閉院',
    ],
    'invalid_office_name_list'         => [
        'テスト',
    ],
    'invalid_addr1'                    => [
        99,
    ],
];
