target_tables: |
  blog
  company
  employ_inquiry
  inquiry
  kaitou
  kurohon_purchase_information
  master_addr1_mst
  master_addr2_mst
  master_area_near_mst
  master_emp_type_mst
  master_entry_course_mst
  master_feed_lp
  master_glp_template
  master_job_type_mst
  master_license_mst
  master_req_date_mst
  master_zip_mst
  parameter_master
  staff
  users
  woa_area_condition_aggregate
  woa_customer
  woa_customer_digs
  woa_matching
  woa_opportunity
  hubspot_token
  registration_inquiry_detail
  staff_examples
  friend_referral
  master_consultant_mst
  woa_customer_tracking_mappings
