CREATE TABLE `blog` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `type` int(2) DEFAULT NULL COMMENT '0:blog\n1:colum\n2:experience\n',
  `post_date` date DEFAULT NULL,
  `title` varchar(200) DEFAULT NULL,
  `post_data` text,
  `colum_id` int(11) DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `del_flg` int(2) DEFAULT '0',
  `list_image` varchar(300) DEFAULT NULL,
  `category_id` int(11) DEFAULT NULL COMMENT '0:blog時　genre_id 15のID',
  `open_flg` int(2) DEFAULT '0' COMMENT '0: draft\n1: open',
  `category_2` int(11) DEFAULT NULL,
  `category_3` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=7848 DEFAULT CHARSET=utf8mb4;

CREATE TABLE `company` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `company_name` varchar(200) DEFAULT NULL,
  `company_kana_name` varchar(200) DEFAULT NULL,
  `comapny_description` text,
  `post_code` varchar(20) DEFAULT NULL,
  `address` varchar(200) DEFAULT NULL,
  `tantou_katagaki` varchar(100) DEFAULT NULL,
  `tantou_name` varchar(100) DEFAULT NULL,
  `tantou_title1` varchar(200) DEFAULT NULL,
  `tantou_title2` varchar(200) DEFAULT NULL,
  `tantou_title3` varchar(200) DEFAULT NULL,
  `tantou_description` text,
  `tantou_message1` text,
  `tantou_message2` text,
  `tantou_message3` text,
  `point_title1` varchar(200) DEFAULT NULL,
  `point_title2` varchar(200) DEFAULT NULL,
  `point_title3` varchar(200) DEFAULT NULL,
  `point_description1` text,
  `point_description2` text,
  `point_description3` text,
  `senpai_title1` varchar(200) DEFAULT NULL,
  `senpai_title2` varchar(200) DEFAULT NULL,
  `senpai_title3` varchar(200) DEFAULT NULL,
  `senpai_caption1` varchar(200) DEFAULT NULL,
  `senpai_caption2` varchar(200) DEFAULT NULL,
  `senpai_caption3` varchar(200) DEFAULT NULL,
  `senpai_message1` text,
  `senpai_message2` text,
  `senpai_message3` text,
  `tantou_message_image1` varchar(200) DEFAULT NULL,
  `tantou_message_image2` varchar(200) DEFAULT NULL,
  `tantou_message_image3` varchar(200) DEFAULT NULL,
  `tantou_image` varchar(200) DEFAULT NULL,
  `senpai_image1` varchar(200) DEFAULT NULL,
  `senpai_image2` varchar(200) DEFAULT NULL,
  `senpai_image3` varchar(200) DEFAULT NULL,
  `sf_office_id` varchar(50) DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `del_flg` int(2) DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=14837 DEFAULT CHARSET=utf8mb4;

CREATE TABLE `employ_inquiry` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `site_id` int(11) DEFAULT NULL,
  `company_name` varchar(255) DEFAULT NULL,
  `shisetsukeitai` varchar(255) DEFAULT NULL,
  `name_kan` varchar(80) DEFAULT NULL,
  `name_cana` varchar(255) DEFAULT NULL,
  `division_name` varchar(255) DEFAULT NULL,
  `addr1` int(11) NOT NULL,
  `addr2` int(11) NOT NULL,
  `addr3` varchar(255) NOT NULL,
  `tel` varchar(20) NOT NULL,
  `mail` varchar(80) NOT NULL,
  `business` varchar(255) DEFAULT NULL,
  `inquiry` varchar(255) DEFAULT NULL,
  `inquiry_detail` varchar(3000) DEFAULT NULL,
  `tel_time_id` varchar(255) DEFAULT NULL,
  `tel_time_note` varchar(3000) DEFAULT NULL,
  `stop_reason` varchar(100) DEFAULT NULL,
  `action1` varchar(255) DEFAULT NULL,
  `action2` varchar(255) DEFAULT NULL,
  `account` varchar(255) DEFAULT NULL,
  `sent_address` varchar(80) DEFAULT NULL,
  `order_tel_contact` varchar(80) DEFAULT NULL,
  `shubetu` varchar(80) DEFAULT NULL,
  `salesforce_flag` int(11) NOT NULL DEFAULT '0',
  `boshu_shikaku` varchar(255) DEFAULT NULL,
  `regist_date` datetime NOT NULL,
  `update_date` datetime NOT NULL,
  `delete_date` datetime DEFAULT NULL,
  `delete_flag` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=456 DEFAULT CHARSET=utf8mb4;

CREATE TABLE `inquiry` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `type` int(11) DEFAULT NULL COMMENT '1:contact\n2:tour\n\n9:sokuhou_email\n10: jinzaisyoukai_moushikomi',
  `contact_syubetsu` int(11) DEFAULT NULL,
  `name` varchar(200) DEFAULT NULL,
  `kana_name` varchar(200) DEFAULT NULL,
  `email` varchar(200) DEFAULT NULL,
  `address` varchar(200) DEFAULT NULL,
  `tel` varchar(45) DEFAULT NULL,
  `age` varchar(45) DEFAULT NULL,
  `seibetsu` int(2) DEFAULT NULL,
  `toiawase` text,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `del_flg` int(2) DEFAULT '0',
  `birth` varchar(45) DEFAULT NULL,
  `shikaku` int(3) DEFAULT NULL,
  `near_station` varchar(200) DEFAULT NULL,
  `question` varchar(200) DEFAULT NULL,
  `syokushu` varchar(200) DEFAULT NULL,
  `company_name` varchar(200) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=2241 DEFAULT CHARSET=utf8mb4;

CREATE TABLE `kaitou` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `title` varchar(200) DEFAULT NULL,
  `shiken_date` date DEFAULT NULL,
  `kaitou_image1` varchar(200) DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `del_flg` int(2) DEFAULT '0',
  `kaitou_image2` varchar(200) DEFAULT NULL,
  `kaitou_image3` varchar(200) DEFAULT NULL,
  `kaitouurl` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=32 DEFAULT CHARSET=utf8mb4;

CREATE TABLE `kurohon_purchase_information` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `user_id` varchar(255) DEFAULT NULL,
  `name_kan` varchar(64) DEFAULT NULL,
  `name_cana` varchar(64) DEFAULT NULL,
  `zip_code` varchar(8) DEFAULT NULL,
  `prefecture` int(11) DEFAULT NULL,
  `city` int(11) DEFAULT NULL,
  `house_number` varchar(255) DEFAULT NULL,
  `tel` varchar(20) DEFAULT NULL,
  `mail` varchar(80) DEFAULT NULL,
  `regist_date` datetime NOT NULL,
  `update_date` datetime NOT NULL,
  `delete_date` datetime DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=8665 DEFAULT CHARSET=utf8mb4;

CREATE TABLE `master_addr1_mst` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `addr0_id` int(11) NOT NULL,
  `addr1` varchar(64) NOT NULL,
  `addr1_roma` varchar(64) DEFAULT NULL,
  `woa_sort` int(11) NOT NULL DEFAULT '0',
  `regist_date` datetime NOT NULL,
  `update_date` datetime DEFAULT NULL,
  `delete_date` datetime DEFAULT NULL,
  `delete_flag` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `idx_addr1` (`addr1`)
) ENGINE=InnoDB AUTO_INCREMENT=89 DEFAULT CHARSET=utf8mb4;

CREATE TABLE `master_addr2_mst` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `addr1_id` int(11) NOT NULL,
  `addr2` varchar(64) NOT NULL,
  `addr2_cana` varchar(64) DEFAULT NULL,
  `addr2_roma` varchar(64) NOT NULL,
  `lat` decimal(10,7) DEFAULT NULL,
  `lng` decimal(10,7) DEFAULT NULL,
  `sort` int(11) NOT NULL DEFAULT '0',
  `woa_sort` int(11) NOT NULL DEFAULT '0',
  `regist_date` datetime NOT NULL,
  `update_date` datetime DEFAULT NULL,
  `delete_date` datetime DEFAULT NULL,
  `delete_flag` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `addr2` (`addr1_id`,`delete_flag`),
  KEY `idx_id_ptotsort` (`id`),
  KEY `idx_id_cjbsort` (`id`),
  KEY `idx_sys_city` (`delete_flag`,`addr1_id`,`id`),
  KEY `idx_addr2` (`addr2`)
) ENGINE=InnoDB AUTO_INCREMENT=89000 DEFAULT CHARSET=utf8mb4;

CREATE TABLE `master_area_near_mst` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `prefecture_id` int(11) NOT NULL,
  `prefecture_name` varchar(64) NOT NULL,
  `city_id` int(11) NOT NULL,
  `city_name` varchar(64) NOT NULL,
  `apply_prefecture_id` int(11) NOT NULL,
  `apply_prefecture_name` varchar(64) NOT NULL,
  `apply_city_id` int(11) NOT NULL,
  `apply_city_name` varchar(64) NOT NULL,
  `regist_date` datetime NOT NULL,
  `update_date` datetime NOT NULL,
  `delete_date` datetime DEFAULT NULL,
  `delete_flag` int(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=9700 DEFAULT CHARSET=utf8mb4;

CREATE TABLE `master_emp_type_mst` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `emp_type` varchar(64) NOT NULL,
  `woa_sort` int(11) NOT NULL DEFAULT '0',
  `bit_arr` varchar(2) DEFAULT NULL,
  `regist_date` datetime NOT NULL,
  `update_date` datetime DEFAULT NULL,
  `delete_date` datetime DEFAULT NULL,
  `delete_flag` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `emp_type_mst_emp_type_key` (`emp_type`)
) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8mb4;

CREATE TABLE `master_entry_course_mst` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `sfid` varchar(100) DEFAULT NULL,
  `query` varchar(100) DEFAULT NULL,
  `entry_category` varchar(100) DEFAULT NULL,
  `entry_course_category` varchar(100) DEFAULT NULL,
  `entry_course_detail` varchar(100) DEFAULT NULL,
  `tmp_value_1` varchar(100) DEFAULT NULL,
  `tmp_value_2` varchar(100) DEFAULT NULL,
  `tmp_value_3` varchar(100) DEFAULT NULL,
  `tmp_value_4` varchar(100) DEFAULT NULL,
  `tmp_value_5` varchar(100) DEFAULT NULL,
  `regist_date` datetime DEFAULT NULL,
  `update_date` datetime DEFAULT NULL,
  `delete_date` datetime DEFAULT NULL,
  `delete_flag` int(1) DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=4826 DEFAULT CHARSET=utf8mb4;

CREATE TABLE `master_feed_lp` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `feed_id` varchar(16) NOT NULL COMMENT 'ID',
  `ab_test` int(11) NOT NULL DEFAULT '0',
  `regist_date` datetime NOT NULL,
  `update_date` datetime NOT NULL,
  `delete_date` datetime DEFAULT NULL,
  `delete_flag` int(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4;

CREATE TABLE `master_glp_template` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `lp_id` varchar(16) NOT NULL COMMENT 'LPID',
  `pc_template` varchar(16) NOT NULL,
  `pc_template_b` varchar(16) NOT NULL,
  `pc_update_date` datetime NOT NULL COMMENT '最終更新日時(PC)',
  `sp_template` varchar(16) NOT NULL,
  `sp_template_b` varchar(16) NOT NULL,
  `sp_update_date` datetime NOT NULL COMMENT '最終更新日時(SP)',
  `site_type` varchar(20) DEFAULT NULL,
  `regist_date` datetime NOT NULL COMMENT '登録日時',
  `update_date` datetime NOT NULL COMMENT '更新日時',
  `delete_date` datetime DEFAULT NULL COMMENT '削除日時',
  `delete_flag` int(1) NOT NULL DEFAULT '0' COMMENT '削除フラグ',
  PRIMARY KEY (`id`),
  UNIQUE KEY `lp_id` (`lp_id`,`site_type`),
  KEY `lp_id_2` (`lp_id`)
) ENGINE=InnoDB AUTO_INCREMENT=31 DEFAULT CHARSET=utf8mb4;

CREATE TABLE `master_job_type_mst` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `job_type` varchar(255) DEFAULT NULL,
  `woa_sort` int(11) NOT NULL DEFAULT '0',
  `regist_date` datetime NOT NULL,
  `update_date` datetime NOT NULL,
  `delete_date` datetime DEFAULT NULL,
  `delete_flag` int(11) DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=100 DEFAULT CHARSET=utf8mb4;

CREATE TABLE `master_license_mst` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `license` varchar(128) NOT NULL,
  `woa_sort` int(11) NOT NULL DEFAULT '0',
  `regist_date` datetime NOT NULL,
  `update_date` datetime DEFAULT NULL,
  `delete_date` datetime DEFAULT NULL,
  `delete_flag` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=47 DEFAULT CHARSET=utf8mb4;

CREATE TABLE `master_req_date_mst` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `req_date` varchar(32) NOT NULL,
  `woa_sort` int(11) NOT NULL DEFAULT '0',
  `start_date` int(11) NOT NULL,
  `end_date` int(11) NOT NULL,
  `regist_date` datetime NOT NULL,
  `update_date` datetime DEFAULT NULL,
  `delete_date` datetime DEFAULT NULL,
  `delete_flag` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=11 DEFAULT CHARSET=utf8mb4;

CREATE TABLE `master_zip_mst` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `zip1` varchar(3) DEFAULT NULL,
  `zip2` varchar(4) DEFAULT NULL,
  `addr1` varchar(32) DEFAULT NULL,
  `addr2` varchar(32) DEFAULT NULL,
  `addr3` varchar(64) DEFAULT NULL,
  `regist_date` datetime NOT NULL,
  `update_date` datetime DEFAULT NULL,
  `delete_date` datetime DEFAULT NULL,
  `delete_flag` int(11) NOT NULL DEFAULT '0',
  `addr_full` varchar(128) NOT NULL DEFAULT '',
  `lat` float(10,6) DEFAULT NULL,
  `lng` float(10,6) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `mz_zip` (`zip1`,`zip2`),
  KEY `idx_addr1` (`addr1`),
  KEY `idx_addr2` (`addr2`)
) ENGINE=InnoDB AUTO_INCREMENT=123219 DEFAULT CHARSET=utf8;

CREATE TABLE `parameter_master` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `genre_id` int(11) DEFAULT NULL,
  `key_value` int(11) DEFAULT NULL,
  `value1` varchar(200) DEFAULT NULL,
  `value2` varchar(200) DEFAULT NULL,
  `value3` varchar(200) DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `del_flg` int(2) DEFAULT '0',
  `value4` text,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=241 DEFAULT CHARSET=utf8mb4;

CREATE TABLE `staff` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(100) DEFAULT NULL,
  `staff_image_path` varchar(200) DEFAULT NULL,
  `from_place` varchar(100) DEFAULT NULL,
  `zayuu` varchar(100) DEFAULT NULL,
  `sonkei` varchar(100) DEFAULT NULL,
  `caption` varchar(200) DEFAULT NULL,
  `question1` text,
  `question2` text,
  `question3` text,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `del_flg` int(2) DEFAULT '0',
  `type` int(11) DEFAULT '0' COMMENT '1:キャリアコンサルタント\n2:アソシエイト',
  `redirect_id` varchar(100) DEFAULT NULL,
  `catchcopy` varchar(200) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=36 DEFAULT CHARSET=utf8mb4;

CREATE TABLE `users` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `email` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `password` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `remember_token` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `users_email_unique` (`email`)
) ENGINE=InnoDB AUTO_INCREMENT=25 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `woa_area_condition_aggregate` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `job_type` varchar(128) NOT NULL COMMENT '募集職種',
  `addr1` int(11) DEFAULT '0' COMMENT '都道府県ID',
  `addr2` int(11) DEFAULT '0' COMMENT '市区町村ID',
  `conditions` varchar(128) NOT NULL COMMENT '条件',
  `value` varchar(128) DEFAULT NULL COMMENT '値',
  `search_key` varchar(128) NOT NULL COMMENT '検索キー',
  `sum` int(11) DEFAULT '0' COMMENT '合計',
  `regist_date` datetime DEFAULT NULL COMMENT '登録日',
  `update_date` datetime DEFAULT NULL COMMENT '更新日',
  `delete_date` datetime DEFAULT NULL COMMENT '削除日',
  `delete_flag` int(11) DEFAULT '0' COMMENT '削除フラグ',
  PRIMARY KEY (`id`),
  KEY `idx_amc_aggreagate_job_type` (`job_type`),
  KEY `idx_amc_aggreagate_addr1` (`addr1`),
  KEY `idx_amc_aggreagate_addr2` (`addr2`),
  KEY `idx_addr1_addr2` (`addr1`,`addr2`),
  KEY `idx_amc_aggreagate_conditions` (`conditions`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `woa_customer` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name_kan` varchar(64) DEFAULT NULL,
  `name_cana` varchar(64) DEFAULT NULL,
  `birth` datetime DEFAULT NULL,
  `zip` varchar(8) DEFAULT NULL,
  `addr1` int(11) DEFAULT NULL,
  `addr2` int(11) DEFAULT NULL,
  `addr3` varchar(255) DEFAULT NULL,
  `tel` varchar(20) DEFAULT NULL,
  `mail` varchar(80) DEFAULT NULL,
  `license` varchar(255) DEFAULT NULL,
  `req_emp_type` varchar(255) DEFAULT NULL,
  `req_date` varchar(255) DEFAULT NULL,
  `retirement_intention` varchar(255) DEFAULT NULL,
  `graduation_year` varchar(20) DEFAULT NULL,
  `entry_order` varchar(255) DEFAULT NULL,
  `src_site_name` varchar(64) DEFAULT NULL,
  `src_customer_id` int(11) DEFAULT NULL,
  `introduce_name` varchar(64) DEFAULT NULL,
  `cp_sfid` varchar(64) DEFAULT NULL,
  `action` varchar(255) DEFAULT NULL,
  `action_first` varchar(255) DEFAULT NULL,
  `entry_category_manual` varchar(64) DEFAULT NULL,
  `template_id` varchar(16) DEFAULT NULL,
  `service_usage_intention` char(1) DEFAULT NULL,
  `ip` varchar(255) DEFAULT NULL,
  `ua` varchar(255) DEFAULT NULL,
  `entry_memo` text,
  `agreement_flag` int(1) DEFAULT '0',
  `salesforce_flag` int(11) NOT NULL DEFAULT '0',
  `moving_flg` varchar(10) DEFAULT NULL,
  `entry_route_category` varchar(100) DEFAULT NULL COMMENT '登録経路カテゴリ',
  `regist_date` datetime NOT NULL,
  `update_date` datetime NOT NULL,
  `delete_date` datetime DEFAULT NULL,
  `delete_flag` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=151706 DEFAULT CHARSET=utf8mb4;

CREATE TABLE `woa_customer_digs` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `salesforce_id` varchar(64) DEFAULT NULL COMMENT '求職者SFID',
  `salesforce_id_real` varchar(64) DEFAULT NULL,
  `addr1` int(11) DEFAULT NULL,
  `addr2` int(11) DEFAULT NULL,
  `addr3` varchar(255) DEFAULT NULL,
  `tel` varchar(20) DEFAULT NULL,
  `mail` varchar(80) DEFAULT NULL COMMENT 'メールアドレス',
  `license` varchar(255) DEFAULT NULL,
  `req_emp_type` varchar(255) DEFAULT NULL COMMENT '希望就業形態（雇用形態）',
  `req_date` varchar(255) DEFAULT NULL COMMENT '入職希望時期',
  `retirement_intention` varchar(255) DEFAULT NULL COMMENT '退職意向',
  `graduation_year` varchar(20) DEFAULT NULL,
  `entry_route` int(11) DEFAULT NULL COMMENT '登録経路',
  `action` varchar(255) DEFAULT NULL COMMENT 'アクションパラメータ',
  `action_first` varchar(255) DEFAULT NULL COMMENT 'アクションパラメータ（最初）',
  `template_id` varchar(16) DEFAULT NULL COMMENT 'テンプレート番号',
  `ip` varchar(255) DEFAULT NULL COMMENT 'IP帯域',
  `ua` varchar(255) DEFAULT NULL COMMENT 'ユーザエージェント',
  `web_customer_id` varchar(20) DEFAULT NULL COMMENT 'woa_customer連携用',
  `salesforce_flag` int(11) NOT NULL DEFAULT '0' COMMENT 'SF連携フラグ',
  `moving_flg` varchar(10) DEFAULT NULL,
  `entry_route_category` varchar(100) DEFAULT NULL COMMENT '登録経路カテゴリ',
  `regist_date` datetime NOT NULL COMMENT '登録日',
  `update_date` datetime NOT NULL COMMENT '更新日',
  `delete_date` datetime DEFAULT NULL COMMENT '削除日',
  `delete_flag` int(11) NOT NULL DEFAULT '0' COMMENT '削除フラグ',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=16654 DEFAULT CHARSET=utf8mb4 COMMENT='woa_customer_digs';

CREATE TABLE `woa_matching` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `salesforce_id` varchar(64) DEFAULT NULL,
  `order_salesforce_id` varchar(64) DEFAULT NULL,
  `customer_id` varchar(255) DEFAULT NULL,
  `entry_status` int(11) DEFAULT NULL,
  `action` varchar(255) DEFAULT NULL,
  `action_first` varchar(255) DEFAULT NULL,
  `via_mailmaga_flag` int(11) DEFAULT NULL,
  `salesforce_flag` int(11) NOT NULL DEFAULT '0',
  `regist_date` datetime NOT NULL,
  `update_date` datetime NOT NULL,
  `delete_date` datetime DEFAULT NULL,
  `delete_flag` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `salesforce_flag` (`salesforce_flag`)
) ENGINE=InnoDB AUTO_INCREMENT=823 DEFAULT CHARSET=utf8mb4;

CREATE TABLE `woa_opportunity` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `job_id` int(11) NOT NULL COMMENT 'オーダーID',
  `sf_order_id` varchar(50) NOT NULL COMMENT 'コメディカルオーダーのSFID',
  `sf_account_id` varchar(50) DEFAULT NULL,
  `inq_number` varchar(80) DEFAULT NULL COMMENT '問い合わせ番号',
  `employment_type` varchar(100) DEFAULT NULL COMMENT '雇用形態',
  `detail` varchar(2000) DEFAULT NULL COMMENT '業務内容',
  `salary` varchar(1000) DEFAULT NULL COMMENT '給与',
  `worktime` varchar(2000) DEFAULT NULL COMMENT '勤務時間',
  `closest` varchar(255) DEFAULT NULL COMMENT '交通手段',
  `dayoff` varchar(255) DEFAULT NULL COMMENT '休日',
  `office_name` varchar(255) DEFAULT NULL COMMENT '事業所名',
  `office_name_kana` varchar(255) DEFAULT NULL COMMENT '事業所名かな',
  `company_name` varchar(255) DEFAULT NULL COMMENT '会社名',
  `company_name_kana` varchar(255) DEFAULT NULL COMMENT '会社名かな',
  `medical_category` varchar(255) DEFAULT NULL COMMENT '診療科目',
  `facilities` varchar(255) DEFAULT NULL COMMENT '施設区分',
  `hp_url` varchar(255) DEFAULT NULL COMMENT 'ホームページ',
  `business` varchar(255) DEFAULT NULL COMMENT '施設形態',
  `worklocation` varchar(255) DEFAULT NULL COMMENT 'ホームページ',
  `job_type` varchar(50) DEFAULT NULL COMMENT '募集職種',
  `postal_code` varchar(50) DEFAULT NULL COMMENT '郵便番号',
  `addr1` int(11) DEFAULT '0' COMMENT '都道府県ID',
  `addr2` int(11) DEFAULT '0' COMMENT '市区町村ID',
  `addr` varchar(512) DEFAULT NULL COMMENT '番地以降',
  `g_latitude` int(11) DEFAULT NULL COMMENT '緯度',
  `g_longitude` int(11) DEFAULT NULL COMMENT '軽度',
  `employ` varchar(255) DEFAULT NULL COMMENT '雇用形態ID',
  `station1` varchar(50) DEFAULT NULL COMMENT '最寄駅1',
  `station2` varchar(50) DEFAULT NULL COMMENT '最寄駅2',
  `station3` varchar(50) DEFAULT NULL COMMENT '最寄駅3',
  `minutes_walk1` int(11) DEFAULT NULL COMMENT '最寄駅への所要時間（分）1',
  `minutes_walk2` int(11) DEFAULT NULL COMMENT '最寄駅への所要時間（分）2',
  `minutes_walk3` int(11) DEFAULT NULL COMMENT '最寄駅への所要時間（分）3',
  `prev_year_bounus` varchar(100) DEFAULT NULL COMMENT '前年度賞与実績',
  `annual_income_min` int(11) DEFAULT '0' COMMENT '年収下限',
  `annual_income_max` int(11) DEFAULT '0' COMMENT '年収上限',
  `nenkankyuujitsu` int(11) DEFAULT '0' COMMENT '年間休日',
  `publicly_flag` int(11) DEFAULT '0' COMMENT '事業所名公開フラグ',
  `webpublicly_flag` int(11) DEFAULT '0' COMMENT 'WEB掲載フラグ',
  `exist_order_flag` int(11) DEFAULT '0' COMMENT 'オーダー有無フラグ',
  `ad_attract_stop_flag` int(1) DEFAULT '0' COMMENT '広告集客停止フラグ',
  `pr_flag` int(11) NOT NULL DEFAULT '0' COMMENT 'PR対象フラグ',
  `pr_display_position` int(11) NOT NULL DEFAULT '1' COMMENT 'PR表示位置',
  `order_pr_title` varchar(255) DEFAULT NULL COMMENT 'オーダーPRタイトル',
  `company_id` int(11) DEFAULT NULL,
  `human_resource` mediumtext DEFAULT NULL,
  `hw_flag` int(11) NOT NULL DEFAULT '0' COMMENT 'ハローワーク存在フラグ',
  `last_confirmed_datetime` datetime NOT NULL DEFAULT '1001-01-01 00:00:00',
  `regist_date` datetime NOT NULL COMMENT '登録日',
  `update_date` datetime NOT NULL COMMENT '更新日',
  `delete_date` datetime DEFAULT NULL COMMENT '削除日',
  `delete_flag` int(11) NOT NULL DEFAULT '0' COMMENT '削除フラグ',
  PRIMARY KEY (`id`),
  UNIQUE KEY `job_id` (`job_id`),
  UNIQUE KEY `sf_order_id` (`sf_order_id`)
) ENGINE=InnoDB AUTO_INCREMENT=7636 DEFAULT CHARSET=utf8mb4;

CREATE TABLE `hubspot_token` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `authorization_code` varchar(256) NOT NULL COMMENT '認証コード',
  `access_token` varchar(256) NOT NULL COMMENT 'アクセストークン',
  `refresh_token` varchar(256) NOT NULL COMMENT 'リフレッシュトークン',
  `limit_date` datetime DEFAULT NULL COMMENT '有効期限',
  `regist_date` datetime NOT NULL COMMENT '登録日',
  `update_date` datetime NOT NULL COMMENT '更新日',
  `delete_date` datetime DEFAULT NULL COMMENT '削除日',
  `delete_flag` int(11) NOT NULL DEFAULT '0' COMMENT '削除フラグ',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `registration_inquiry_detail` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(80) DEFAULT NULL COMMENT '名前',
  `url` VARCHAR(255) DEFAULT NULL COMMENT 'SFURL',
  `license` VARCHAR(64) DEFAULT NULL COMMENT '保有職種',
  `addr1_txt` VARCHAR(64) DEFAULT NULL COMMENT '求職者の住まい(都道府県)',
  `age` int(11) DEFAULT 0 COMMENT '年齢',
  `cp_name` VARCHAR(64) DEFAULT NULL COMMENT '担当CP',
  `reentry_contact_time` VARCHAR(255) DEFAULT NULL COMMENT '連絡希望時間帯',
  `inquiry_date` datetime NOT NULL COMMENT '問い合わせ内容（日時）',
  `toiawase` TEXT DEFAULT NULL COMMENT 'お問い合わせ内容',
  `template_id` VARCHAR(16) DEFAULT NULL COMMENT 'テンプレート番号',
  `hub_spot_url` VARCHAR(255) DEFAULT NULL COMMENT 'HubSpotURL',
  `contact_inquiry` VARCHAR(255) DEFAULT NULL COMMENT '先頭問い合わせ項目',
  `graduation_year` VARCHAR(255) DEFAULT NULL COMMENT '卒業予定年',
  `input_birth_year` VARCHAR(20) DEFAULT NULL COMMENT '生年',
  `mob_phone` VARCHAR(20) DEFAULT NULL COMMENT '電話番号',
  `mob_mail` VARCHAR(80) DEFAULT NULL COMMENT 'メールアドレス',
  `regist_date` datetime NOT NULL COMMENT '登録日時',
  `update_date` datetime NOT NULL COMMENT '更新日時',
  `delete_date` datetime DEFAULT NULL COMMENT '削除日時',
  `delete_flag` int(11) NOT NULL DEFAULT 0 COMMENT '削除フラグ',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `staff_examples` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `staff_id` int(11) NOT NULL COMMENT 'Staff Id',
  `example_type` int(11) NOT NULL COMMENT '事例タイプ',
  `age` VARCHAR(10) DEFAULT NULL COMMENT '年代',
  `gender` VARCHAR(10) DEFAULT NULL COMMENT '性別',
  `license` VARCHAR(255) DEFAULT NULL COMMENT '資格',
  `grade` VARCHAR(255) DEFAULT NULL COMMENT '学年',
  `catchphrase` VARCHAR(255) DEFAULT NULL COMMENT 'キャッチフレーズ',
  `worry` VARCHAR(500) DEFAULT NULL COMMENT 'お悩み',
  `research` VARCHAR(500) DEFAULT NULL COMMENT '就活の情報収集',
  `customer_comment` VARCHAR(500) DEFAULT NULL COMMENT '求職者の感想',
  `cp_comment` VARCHAR(500) DEFAULT NULL COMMENT 'CPからの一言',
  `regist_date` datetime NOT NULL COMMENT '登録日時',
  `update_date` datetime NOT NULL COMMENT '更新日時',
  `delete_date` datetime DEFAULT NULL COMMENT '削除日時',
  `delete_flag` int(11) NOT NULL DEFAULT 0 COMMENT '削除フラグ',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `friend_referral` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT 'Id',
  `customer_id` int(11) NOT NULL COMMENT 'WOA求職者Id',
  `cp_sms_id` varchar(64) DEFAULT NULL COMMENT 'CP SMS Id',
  `referral_salesforce_id` varchar(64) DEFAULT NULL COMMENT '紹介者salesforce_id',
  `referral_name` varchar(64) DEFAULT NULL COMMENT '紹介者名',
  `regist_date` datetime NOT NULL COMMENT '登録日時',
  `update_date` datetime NOT NULL COMMENT '更新日時',
  `delete_date` datetime DEFAULT NULL COMMENT '削除日時',
  `delete_flag` int NOT NULL DEFAULT '0' COMMENT '削除フラグ',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `master_consultant_mst` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `sms_id` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  `short_sms_id` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  `role_id` varchar(18) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT '',
  `role_name` varchar(50) NOT NULL DEFAULT '',
  `name` varchar(100) NOT NULL,
  `pc_url` varchar(256) DEFAULT NULL,
  `mb_url` varchar(256) DEFAULT NULL,
  `sp_url` varchar(256) DEFAULT NULL,
  `url_id` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `dept` varchar(100) NOT NULL,
  `group` varchar(100) NOT NULL,
  `name_cana` varchar(100) NOT NULL,
  `mob_phone` varchar(20) DEFAULT NULL,
  `tel` varchar(20) DEFAULT NULL,
  `mob_mail` varchar(256) DEFAULT NULL,
  `pc_mail` varchar(256) DEFAULT NULL,
  `password` varchar(255) DEFAULT NULL,
  `admin_flag` int(11) DEFAULT NULL,
  `pr` text,
  `attitude` text,
  `episode` text,
  `passion` text,
  `status` int(11) NOT NULL,
  `office_name` varchar(256) DEFAULT NULL,
  `officeleader_id` varchar(64) DEFAULT NULL,
  `officeleader_name` varchar(256) DEFAULT NULL,
  `officeleader_mail` text,
  `teamleader_id` varchar(64) DEFAULT NULL,
  `teamleader_name` varchar(256) DEFAULT NULL,
  `teamleader_mail` text,
  `cp_info_hide_flag` int(11) DEFAULT 0,
  `regist_date` datetime NOT NULL,
  `update_date` datetime NOT NULL,
  `delete_date` datetime DEFAULT NULL,
  `delete_flag` int(11) NOT NULL,
  `employee_id` varchar(11) DEFAULT NULL,
  `CASESAFEID_Id` varchar(18) DEFAULT NULL,
  `RoleID_18` varchar(18) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `sms_id` (`sms_id`),
  UNIQUE KEY `url_id` (`url_id`),
  KEY `idx_short_sms_id` (`short_sms_id`),
  KEY `idx_status` (`status`),
  KEY `idx_delete_flag` (`delete_flag`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `woa_customer_tracking_mappings` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `customer_id` varchar(255) NOT NULL COMMENT 'customer_id',
  `customer_id_hash` varchar(255) NOT NULL COMMENT 'ハッシュ化したcustomer_id',
  `upload_status` varchar(255) NOT NULL COMMENT 'アップロードステータス',
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `woa_customer_tracking_mappings_customer_id_unique` (`customer_id`),
  UNIQUE KEY `woa_customer_tracking_mappings_customer_id_hash_unique` (`customer_id_hash`),
  KEY `woa_customer_tracking_mappings_upload_status_index` (`upload_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='ハッシュ化したcustomer_id保持';
