name: Database migrate to development

on:
  pull_request:
    branches:
      - "main"
    types:
      - closed
    paths:
      - 'database/sqldef/schema_development.sql'

jobs:
  build-development:
    name: Development docker build image and push
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read
    environment:
      name: development
      url: https://development.willone.jp/
    steps:
      # https://github.com/aws-actions/configure-aws-credentials#usage
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Use docker-build-push action
        uses: ./.github/actions/docker-build-push
        with:
          AWS_ACCOUNT_ID: ${{ vars.AWS_ACCOUNT_ID }}
          SERVER_TYPE: 'woa_laravel'

  db-migrate:
    name: DB migrate
    runs-on: ubuntu-latest
    needs: build-development
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read
      issues: write
      pull-requests: write
    environment:
      name: development
      url: https://development.willone.jp/
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: DB migrate
        uses: ./.github/actions/db-migrate
        with:
          AWS_ACCOUNT_ID: ${{ vars.AWS_ACCOUNT_ID }}
          ENVIRONMENT: ${{ vars.ENVIRONMENT }}
          ECSPRESSO_CONFIG_NAME: 'oneshot_db_migrate'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DB_MIGRATE_APPLY: 1 # 1のときだけapply。それ以外はdry run
